# Generated by Django 4.2.10 on 2024-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarks",
            field=models.ManyToManyField(
                related_name="bookmark_users", to="articles.article"
            ),
        ),
    ]
